### ISSUE TITLE
welcome.pyの実行エラー

### ISSUE THREAD

**Issue by jmcd-toda** [icoxfog417/baby-steps-of-rl#66]
### 指摘事項

welcome.pyを実行したところエラーが出る。何がおかしいか指摘してほしい。

### 指摘箇所

* [〇] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p６

### 実行環境

* OS:  Windows 10
* Python version: 3.7.13
* `pip freeze`の実行結果 (下に添付)
absl-py==0.15.0
astunparse==1.6.3
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.12
cloudpickle==1.2.2
cycler==0.11.0
flatbuffers==1.12
fonttools==4.31.2
future==0.18.2
gast==0.4.0
google-auth==2.6.2
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.34.1
gym==0.14.0
-e git+https://github.com/lusob/gym-ple.git@7cedbf4e31be86f5ca2aae5c0dfd9d38825af64e#egg=gym_ple
h5py==3.1.0
idna==3.3
importlib-metadata==4.11.3
joblib==1.1.0
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
kiwisolver==1.4.0
Markdown==3.3.6
matplotlib==3.5.1
numpy==1.19.5
oauthlib==3.2.0
opt-einsum==3.3.0
Pillow==9.0.1
-e git+https://github.com/ntasfi/PyGame-Learning-Environment.git@3dbe79dc0c35559bb441b9359948aabf9bb3d331#egg=ple
protobuf==3.19.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pygame==2.0.0
pyglet==1.3.2
Pygments==2.11.2
pyparsing==3.0.7
python-dateutil==2.8.2
pywin32==303
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
scikit-learn==1.0.2
scipy==1.8.0
six==1.15.0
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.5.0
tensorflow-estimator==2.5.0
termcolor==1.1.0
threadpoolctl==3.1.0
tqdm==4.63.1
typing-extensions==3.7.4.3
urllib3==1.26.9
Werkzeug==2.0.3
wincertstore==0.2
wrapt==1.12.1
zipp==3.7.0

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

(rl-book) C:\Users\May1217\baby-steps-of-rl-ja>python welcome.py
Traceback (most recent call last):
File "C:\Users\May1217\miniconda3\envs\rl-book\lib\site-packages\numpy\core_init_.py", line 22, in <module>
from . import multiarray
File "C:\Users\May1217\miniconda3\envs\rl-book\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
from . import overrides
File "C:\Users\May1217\miniconda3\envs\rl-book\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "welcome.py", line 1, in <module>
import numpy as np
File "C:\Users\May1217\miniconda3\envs\rl-book\lib\site-packages\numpy_init_.py", line 140, in <module>
from . import core
File "C:\Users\May1217\miniconda3\envs\rl-book\lib\site-packages\numpy\core_init_.py", line 48, in <module>
raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

The Python version is: Python3.7 from "C:\Users\May1217\miniconda3\envs\rl-book\python.exe"
The NumPy version is: "1.19.5"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by icoxfog417** [comment]
掲載頂いた`welcome.py`の実行で発生したエラーを見ると、Numpyのインストールに失敗しているようです。`welcome.py`でなく、単純に`import numpy as np`でも同様のエラーが発生すると思います(以下は頂いたエラーメッセージの抜粋です)。

```
Traceback (most recent call last):
File "welcome.py", line 1, in
import numpy as np
File "C:\Users\May1217\miniconda3\envs\rl-book\lib\site-packages\numpy_init_.py", line 140, in
from . import core
File "C:\Users\May1217\miniconda3\envs\rl-book\lib\site-packages\numpy\core_init_.py", line 48, in
raise ImportError(msg)
ImportError:
```

このエラーは様々な要因で発生し、Numpy公式がエラーが発生する各状況においてどのような対応を取ればよいかまとめてくれています。メッセージの文中にある通り、以下のページです。

https://numpy.org/devdocs/user/troubleshooting-importerror.html

経験的には、pipとcondaで別々にNumpyをインストールしてしまっている場合、まずどちらかをアンインストールしてください。重複してNumpyがインストールされているとどちらでエラーが発生しているかわからなくなるためです。

なお、エラー文中のNumpyのバージョンである`1.19.5`は本書での環境構築で使用しているバージョン([1.16.4](https://github.com/icoxfog417/baby-steps-of-rl-ja/blob/master/requirements.txt#L3))と異なります。多少バージョンが違っても動作すると思いますが、`welcome.py`以降で動作しない場合バージョンの差異が原因となる可能性があることにご留意ください。

**Comment by jmcd-toda** [comment]
ありがとうございます。確認してみます。
